app:
  namespace: io.codymj
  name: service
  version: 0.0.1

server:
  host: 127.0.0.1
  port: 8080
  timeout:
    read: 5s
    write: 10s
    idle: 15s
    server: 30s

database:
  max_open_conns: 10
  max_idle_conns: 10
  max_idle_time: 15m